ARG BASE_DOCKER=rocm/pytorch:rocm7.1_ubuntu24.04_py3.12_pytorch_release_2.9.1
FROM $BASE_DOCKER

ARG PYTORCH_ROCM_ARCH_OVERRIDE="gfx942"

ENV NO_PROXY=localhost,127.0.0.1,pypi.org,files.pythonhosted.org,raw.githubusercontent.com
ENV WORKSPACE_DIR=/workspace
ENV STAGE_DIR=/workspace/installs
ENV PIP_DEFAULT_TIMEOUT=120
ENV PIP_RETRIES=10
RUN mkdir -p $WORKSPACE_DIR
RUN mkdir -p ${STAGE_DIR}
WORKDIR $WORKSPACE_DIR

# Check python3 version and install respective python3-dev
RUN PY3_VER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')" && \
    if apt-cache show "python${PY3_VER}-dev" >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends "python${PY3_VER}-dev"; \
        # Overwrite python3-config to point to the correct version to prevent mismatch during Megatron-DeepSpeed build
        ln -sf /usr/bin/python${PY3_VER}-config /usr/bin/python3-config; \
    else \
        apt-get install -y --no-install-recommends python3-dev; \
    fi

RUN pip3 install \
scipy \
wheel \
PyGithub \
pytest-xdist \
psutil \
transformers \
einops \
flask-restful \
pytest \
pytest-cov \
pytest_mock \
pytest-csv \
pytest-asyncio \
pytest-random-order \
sentencepiece \
wrapt \
zarr \
wandb \
tensorstore==0.1.45 \
mock \
pybind11 \
'setuptools<82' \
datasets \
tiktoken \
pynvml \
fastapi \
uvicorn

RUN pip install "nltk==3.8.1"

# Install Causal-Conv1d and its dependencies
WORKDIR ${STAGE_DIR}
ENV CAUSAL_CONV1D_FORCE_BUILD=TRUE
ENV MAMBA_FORCE_BUILD=TRUE
ENV HIP_ARCHITECTURES=${PYTORCH_ROCM_ARCH_OVERRIDE}
RUN git clone https://github.com/Dao-AILab/causal-conv1d causal-conv1d &&\
    cd causal-conv1d &&\
    git show --oneline -s &&\
    pip install --no-build-isolation .

# Install mamba
WORKDIR ${STAGE_DIR}
RUN pip install mamba-ssm --no-build-isolation

# Build flash-attention
ARG BUILD_FA="1"
ARG FA_BRANCH="main"
ARG FA_REPO="https://github.com/ROCm/flash-attention.git"
WORKDIR $WORKSPACE_DIR
RUN if [ "$BUILD_FA" -eq "1" ]; then \
git clone ${FA_REPO} \
&& cd flash-attention \
&& git checkout ${FA_BRANCH} \
&& MAX_JOBS=128 GPU_ARCHS=${PYTORCH_ROCM_ARCH_OVERRIDE} python3 setup.py install; \
fi

# Clone TE repo and submodules
WORKDIR ${STAGE_DIR}

ARG TE_COMMIT=release_v2.2_rocm
ENV NVTE_FRAMEWORK=pytorch
ENV PYTORCH_ROCM_ARCH=${PYTORCH_ROCM_ARCH_OVERRIDE}
ENV NVTE_USE_HIPBLASLT=1
ENV NVTE_AITER_PREBUILT_BASE_URL=https://compute-artifactory.amd.com:5000/artifactory/rocm-generic-local/te-ci/aiter-prebuilts

RUN git clone --recursive https://github.com/ROCm/TransformerEngine.git && \
    cd TransformerEngine && \
    git checkout ${TE_COMMIT} && \
    git submodule update --init --recursive && \
    echo "TransformerEngine at commit:" $(git rev-parse HEAD) && \
    pip install --no-build-isolation .

RUN git clone https://github.com/caaatch22/grouped_gemm.git &&\
    cd grouped_gemm &&\
    git checkout rocm &&\
    git submodule update --init --recursive &&\
    pip install --no-build-isolation .


RUN git clone https://github.com/NVIDIA-NeMo/Emerging-Optimizers.git &&\
    cd Emerging-Optimizers &&\
    git checkout v0.1.0 &&\
    pip install --no-build-isolation .

RUN git clone https://github.com/NVIDIA/nvidia-resiliency-ext && \
    cd nvidia-resiliency-ext && \
    git checkout v0.6.0 && \
    STRAGGLER_DET_SKIP_CUPTI_EXT_BUILD=1 pip install .

WORKDIR $WORKSPACE_DIR
COPY . Megatron-LM
WORKDIR $WORKSPACE_DIR/Megatron-LM
RUN pip install -e .

ENV PYTHONPATH=/var/lib/jenkins/triton/python

# record configuration for posterity
RUN pip list
